### ISSUE TITLE
One Problem about how to automatic end the progress?

### ISSUE THREAD

**Issue by sddwt** [monkeyWie/docker-web-terminal#2]
Accorrding to your code, I noticed that the attach will be closed only the ws closed, 
However, after many times I used the console, I noticed that there were many sh/Script progress when I seeing "top", so I want to know how to automaticly end the progress after I quit the page?
Thank you :)

**Comment by monkeyWie** [comment]
When you quit the page, it will trigger ws close，so don’t worry about it.
